name: Deploy Sphinx documentation to Pages

on:
  push:
    branches:
      - master # Or your default branch name

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: pip install Sphinx # Install Sphinx and any other required packages
      - name: Build Sphinx docs
        run: sphinx-build -b html docs/ docs/_build/html # Adjust paths as needed
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html' # The directory containing your built HTML files
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
